---
ACL:
  opaque: |
    Q0ECACgFCAAAAAAABQCEAxAA1AP0AwEAAAAoAAQAAAAEACgAVgMMADI2LzAzLzIwMjQgMDk6MDI6MzYg
    UE0gU2VyZGFyIEJhc2VnbWV6L2RldmVsb3BpIHVwZGF0ZWQgTlNGT0RQUmVtb3RlVXNlcgAyNi8wMy8y
    MDI0IDA5OjAyOjAxIFBNIFNlcmRhciBCYXNlZ21lei9kZXZlbG9waSB1cGRhdGVkIE5TRk9EUFJlbW90
    ZVVzZXIAMjYvMDMvMjAyNCAwOTowMTo1NyBQTSBTZXJkYXIgQmFzZWdtZXovZGV2ZWxvcGkgYWRkZWQg
    TlNGT0RQUmVtb3RlVXNlcgAyNi8wMy8yMDI0IDA4OjU5OjA3IFBNIFNlcmRhciBCYXNlZ21lei9kZXZl
    bG9waSB1cGRhdGVkIExvY2FsRG9tYWluQWRtaW5zADI2LzAzLzIwMjQgMDg6NTk6MDEgUE0gU2VyZGFy
    IEJhc2VnbWV6L2RldmVsb3BpIGFkZGVkIExvY2FsRG9tYWluQWRtaW5zADI2LzAzLzIwMjQgMDg6NTg6
    NTQgUE0gU2VyZGFyIEJhc2VnbWV6L2RldmVsb3BpIHVwZGF0ZWQgLURlZmF1bHQtADI2LzAzLzIwMjQg
    MDg6NTg6NDcgUE0gU2VyZGFyIEJhc2VnbWV6L2RldmVsb3BpIGFkZGVkIEFub255bW91cwAyNi8wMy8y
    MDI0IDA1OjQwOjQ1IFBNIFNlcmRhciBCYXNlZ21lei9kZXZlbG9waSBhZGRlZCBPdGhlckRvbWFpblNl
    cnZlcnMAMjYvMDMvMjAyNCAwNTo0MDo0NSBQTSBTZXJkYXIgQmFzZWdtZXovZGV2ZWxvcGkgYWRkZWQg
    TG9jYWxEb21haW5TZXJ2ZXJzADI2LzAzLzIwMjQgMDU6NDA6NDUgUE0gU2VyZGFyIEJhc2VnbWV6L2Rl
    dmVsb3BpIGFkZGVkIG1hZ2dpZS9kZXZlbG9waQAyNi8wMy8yMDI0IDA1OjQwOjQ1IFBNIFNlcmRhciBC
    YXNlZ21lei9kZXZlbG9waSBhZGRlZCBTZXJkYXIgQmFzZWdtZXovZGV2ZWxvcGkAMjYvMDMvMjAyNCAw
    NTo0MDo0NSBQTSBTZXJkYXIgQmFzZWdtZXovZGV2ZWxvcGkgdXBkYXRlZCAtRGVmYXVsdC0AAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIFlgREBAAAAAC+BAAAAAAAAAAA3AQAABIEAAAAAAAARUEEAAAA
    AAAAAAAAAAAEBgkALURlZmF1bHQtAAAARUEGAAAAAAAAAAAAAAC4Bx0AQ049U2VyZGFyIEJhc2VnbWV6
    L089ZGV2ZWxvcGkAAABFQQYAAAAAAAAAAAAAAJqHFABDTj1tYWdnaWUvTz1kZXZlbG9waQAAAABFQQYA
    AAAAAAAAAAAAANoHEgBMb2NhbERvbWFpblNlcnZlcnMAAAAARUEAAAAAAAAAAAAAAABCEBIAT3RoZXJE
    b21haW5TZXJ2ZXJzAAAAAEVBAAAAAAAAAAAAAAAABRAJAEFub255bW91cwBuBEVBBgAAAAAAAAAAAAAA
    +AcRAExvY2FsRG9tYWluQWRtaW5zAAAARUEFAAAAAAAAAAAAAAD4BxAATlNGT0RQUmVtb3RlVXNlcgAA
DBOptions: 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0